### ISSUE TITLE
Feature request: support for "Import DPM Configuration"

### ISSUE THREAD

**Issue by EdGue42** [zhmcclient/zhmccli#243]
Request to support endpoint:

**Import DPM Configuration**

_The Import DPM Configuration operation imports DPM objects such as partitions, NICs, HBAs,
virtual functions, and their properties. It also restores DPM-specific CPC properties, like the description,
auto-start partition list and capacity groups._

**Comment by andy-maier** [comment]
The import and export DPM config function has been merged into the zhmcclient master and will be in zhmcclient version 1.1.0.

**Comment by andy-maier** [comment]
PR #248 addresses this request and also provides a DPM export functionality.
