### ISSUE TITLE
Create user issue on z14

### ISSUE THREAD

**Issue by LutinGit** [zhmcclient/zhmccli#286]
### Actual behavior
zhmc user create --name testuser --password-rule Basic --password test
Error: HTTPError: 400,6: The JSON object contains an unrecognized field ('mfa-types') [POST /api/console/users]

### Expected behavior
zhmc user create --name testuser --password-rule Basic --password test
New user 'testuser' has been created.

### Execution environment

* zhmccli version: 1.2.0
* zhmcclient version: 1.2.1
* Operating system (type+version): Windows 2016
* HMC version: 2.14.1
* CPC version: 3906

**Comment by andy-maier** [comment]
Accepted, needs to be fixed.

**Comment by andy-maier** [comment]
The fix will be in 1.3.0 and 1.2.2.
