### ISSUE TITLE
Firewall port opening in documentation.

### ISSUE THREAD

**Issue by Paddey** [zhmcclient/zhmccli#332]
Hello, 
Are any specific ports on the client side should open on firewall to be able zhmc manage HMC console?
Where to get the list of open ports on firewall for zhmcli uasge?
Regards,

**Comment by andy-maier** [comment]
Hello. Sorry for the delay.
The ports to open are 6794 (for the HMC REST API) and 61612 (for notifications via JMS over STOMP).
They are documented In the HMC WS API book.

While the zhmccli project has a [Setting up the HMC](https://zhmccli.readthedocs.io/en/latest/intro.html#setting-up-the-hmc) chapter, it does not document anything for the case of a proxy or firewall (such as the ports to be opened). We will add that to the docs.
