### ISSUE TITLE
Log off from temporary session

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmccli#421]
The zhmc command currently does not log off from a temporary session it created. For the `session create` command that is the desired behavior, but all other created sessions are considered temporary sessions because there is no way to reuse them in subsequent zhmc commands. The issue is that the temporary session stays open on the HMC and that every zhmc command creates a new session on the HMC, causing the HMC to be out of sessions at some point.

Add support for automatically logging off from temporary sessions.

**Comment by rjbrenn** [comment]
Are you able to pin down a release or date when this issue first appeared in zhmcclient ?  We're chasing an issue that looks like this and are tryingt o determine whether its this issue or something else entirely.

**Comment by andy-maier** [comment]
The zhmc cli command apparently never logged off automatically. We use it a lot with "zhmc session create", so the number of sessions used is significantly reduced compared to logging on for every command separately, and that's why we never had an issue with that.

At the level of the zhmcclient library, it was always possible to properly log off, but you needed to code that in your program using the library (which the zhmc CLI did not do properly).

I found that as part of fixing this in the zhmc CLI, some improvements are needed in the zhmcclient library, though. They will be in https://github.com/zhmcclient/python-zhmcclient/pull/1184

**Comment by andy-maier** [comment]
@rjbrenn @eaibmz PR https://github.com/zhmcclient/zhmccli/pull/422 addresses this issue in the future 1.8.0 version, and PR #423 rolls it back to 1.7.1. Please try it out.
