### ISSUE TITLE
docs: inconsistent naming of credential variables

### ISSUE THREAD

**Issue by markuszoeller** [zhmcclient/zhmccli#45]
Most of the time, the docs talk about `ZHMC_USER` and `ZHMC_HOST` but on few occasions about `hmc_userid` and `hmc_host`. I'm not sure if it is a bug, it only confused me a little.
The examples work if you read them carefully, but a bit more consistency might be helpful.

NOTE: This report is about the naming, and not about the upper-case/lower-case difference.

### Actual behavior

```
.. code-block:: text

    $ hmc_host="<IP address or hostname of the HMC>"
    $ hmc_userid="<userid on that HMC>"
    $ zhmc -h $hmc_host -u $hmc_userid cpc list
    Enter password (for user <hmc_user> at HMC <hmc_host>): .......
    +----------+------------------+
    | name     | status           |
    |----------+------------------|
    | P000S67B | service-required |
    +----------+------------------+
```

### Expected behavior

```
.. code-block:: text

    $ zhmc_host="<IP address or hostname of the HMC>"
    $ zhmc_user="<userid on that HMC>"
    $ zhmc -h $zhmc_host -u $zhmc_user cpc list
    Enter password (for user <zhmc_user> at HMC <zhmc_host>): .......
    +----------+------------------+
    | name     | status           |
    |----------+------------------|
    | P000S67B | service-required |
    +----------+------------------+
```

### Execution environment

* zhmccli version: 0.18.0
* zhmcclient version: 0.19.0
* Operating system (type+version): N/A
* HMC version: /NA
* CPC version: N/A

**Comment by andy-maier** [comment]
In the quoted examples, "hmc_host" etc are shell variables that can have any name, while the ZHMC_... variables are environment variables that must have exactly that name. PR #205 cleans up the quoted examples somewhat.
