### ISSUE TITLE
Support of new MCL install and delete APIs for CPC

### ISSUE THREAD

**Issue by schaufle** [zhmcclient/zhmccli#528]
With bundle s23 WSWAPIs for handlinge Z MCLs were introduce on z16.
Please add support in zhmccli to call those new APIs. They are
- "Remove and activate"
- "Install and activae"
- "Delete retrieved internal code"
Those exist for both CPC and console.

**Comment by andy-maier** [comment]
This requires support for these operations in the zhmcclient library. See https://github.com/zhmcclient/python-zhmcclient/issues/1357

**Comment by andy-maier** [comment]
The zhmcclient implemented support for "Install and activate" and "Delete retrieved internal code" in PR https://github.com/zhmcclient/python-zhmcclient/pull/1362 (version 1.13.0). We discussed "Remove and activate" and it was deemed too dangerous and should remain an activity triggered by the PE at the GUI.

With that, this item here is reduced to implement "Install and activate" and "Delete retrieved internal code" for the zhmccli.
