### ISSUE TITLE
Dump option for the DPM mode

### ISSUE THREAD

**Issue by stzi-de** [zhmcclient/zhmccli#70]
### Actual behavior
Currently it is only possible to dump a LPAR that are not in the DPM mode. You can do it with "lpar load..." For partition option is it not available. On the HMC GUI is it possible.

### Expected behavior
Dump also a DPM system.

### Execution environment

* zhmccli version: current master
* zhmcclient version: -
* Operating system (type+version): fedora 31
* HMC version: -
* CPC version: all

**Comment by mhartmay** [comment]
I will create a pull request for this feature in the next days.

**Comment by andy-maier** [comment]
@mhartmay I have created the PR from your branch.

**Comment by andy-maier** [comment]
At this point, PR #88 is ready for partial review, see there for details.

**Comment by andy-maier** [comment]
PR #88 was merged and is targeted for the upcoming release, version 0.20.0.
